#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tarmo_Kalk.Resource", IsApplication=true)]

namespace Tarmo_Kalk
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001c
			public const int button_0 = 2131034140;
			
			// aapt resource value: 0x7f050016
			public const int button_1 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int button_2 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int button_3 = 2131034136;
			
			// aapt resource value: 0x7f050010
			public const int button_4 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int button_5 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int button_6 = 2131034130;
			
			// aapt resource value: 0x7f05000a
			public const int button_7 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int button_8 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int button_9 = 2131034124;
			
			// aapt resource value: 0x7f050013
			public const int button__min = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int button_backspace = 2131034119;
			
			// aapt resource value: 0x7f05001a
			public const int button_clear = 2131034138;
			
			// aapt resource value: 0x7f050005
			public const int button_cos = 2131034117;
			
			// aapt resource value: 0x7f05001e
			public const int button_decimal = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int button_div = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int button_equals = 2131034144;
			
			// aapt resource value: 0x7f050019
			public const int button_multiply = 2131034137;
			
			// aapt resource value: 0x7f05000d
			public const int button_plus = 2131034125;
			
			// aapt resource value: 0x7f05001d
			public const int button_posNeg = 2131034141;
			
			// aapt resource value: 0x7f05000e
			public const int button_qubed = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int button_sin = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int button_sqared = 2131034120;
			
			// aapt resource value: 0x7f050014
			public const int button_sqrt = 2131034132;
			
			// aapt resource value: 0x7f050006
			public const int button_tan = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int editText1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int gridLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int tableLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int tableRow2 = 2131034121;
			
			// aapt resource value: 0x7f05000f
			public const int tableRow3 = 2131034127;
			
			// aapt resource value: 0x7f05001b
			public const int tableRow4 = 2131034139;
			
			// aapt resource value: 0x7f050015
			public const int tableRow5 = 2131034133;
			
			// aapt resource value: 0x7f050003
			public const int tableRow7 = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
